# Generated by Django 3.0.2 on 2020-02-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customernumber', models.IntegerField(db_column='customerNumber', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='customerName', max_length=50)),
                ('contactlastname', models.CharField(db_column='contactLastName', max_length=50)),
                ('contactfirstname', models.CharField(db_column='contactFirstName', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('creditlimit', models.FloatField(blank=True, db_column='creditLimit', null=True)),
                ('customerlocation', models.TextField(db_column='customerLocation')),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeenumber', models.IntegerField(db_column='employeeNumber', primary_key=True, serialize=False)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(db_column='jobTitle', max_length=50)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('officecode', models.CharField(db_column='officeCode', max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(db_column='postalCode', max_length=15)),
                ('territory', models.CharField(max_length=10)),
                ('officelocation', models.TextField(db_column='officeLocation')),
            ],
            options={
                'db_table': 'Offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordernumber', models.IntegerField(db_column='orderNumber', primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(db_column='orderDate')),
                ('requireddate', models.DateTimeField(db_column='requiredDate')),
                ('shippeddate', models.DateTimeField(blank=True, db_column='shippedDate', null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('checknumber', models.CharField(db_column='checkNumber', max_length=50, primary_key=True, serialize=False)),
                ('paymentdate', models.DateTimeField(db_column='paymentDate')),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'Payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('productline', models.CharField(db_column='productLine', max_length=50, primary_key=True, serialize=False)),
                ('textdescription', models.CharField(blank=True, db_column='textDescription', max_length=4000, null=True)),
                ('htmldescription', models.TextField(blank=True, db_column='htmlDescription', null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ProductLines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productcode', models.CharField(db_column='productCode', max_length=15, primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productName', max_length=70)),
                ('productscale', models.CharField(db_column='productScale', max_length=10)),
                ('productvendor', models.CharField(db_column='productVendor', max_length=50)),
                ('productdescription', models.TextField(db_column='productDescription')),
                ('quantityinstock', models.SmallIntegerField(db_column='quantityInStock')),
                ('buyprice', models.FloatField(db_column='buyPrice')),
                ('msrp', models.FloatField(db_column='MSRP')),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('productcode', models.OneToOneField(db_column='productCode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classic_app.Products')),
                ('quantityordered', models.IntegerField(db_column='quantityOrdered')),
                ('priceeach', models.FloatField(db_column='priceEach')),
                ('orderlinenumber', models.SmallIntegerField(db_column='orderLineNumber')),
            ],
            options={
                'db_table': 'OrderDetails',
                'managed': False,
            },
        ),
    ]
